language: node_js

sudo: false

notifications:
    email:
        on_failure: always
        on_success: change

node_js:
    - "5"
    - "5.1"
    - "iojs"

before_install:
    - npm install -g bower
    
script:
    - node_modules/.bin/karma start ./src/spec/karma.conf.ci.js
