language: node_js

sudo: false

notifications:
    email:
        on_failure: always
        on_success: change

node_js:
    - "5"
    - "5.1"
    - "iojs"

before_install:
    - npm install -g bower
    
script:
    - npm run test-ci && cat ./dist/overage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./dist/coverage
