language: node_js

sudo: false

notifications:
  email:
    on_failure: always
    on_success: change

node_js:
  - "5"
  - "5.1"
  - "iojs"
  
before_script:
  - npm install -g bower
  - bower install